#Server port :
server.port= 8813

#Application name :
spring.application.name= order-service

#Client registration properties:
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Data source :
spring.datasource.url=jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = update
spring.h2.console.enabled=true

#Redis
#spring.session.redis.namespace=session
spring.session.store-type=none
#spring.session.jdbc.initialize-schema=always
#spring.redis.host=localhost
#spring.redis.port=6379



